config/routes.rb
WardAreaBook::Application.routes.draw do

  match '/faq' => 'static_pages#faq'

  match '/action_items/wardActionItems/' => 'action_items#wardActionItems'
  resources :action_items, :only => [:create, :update, :destroy]
  resources :comments, :only => [:update, :destroy]

  get '/teaching_routes' => 'teaching_routes#index'
  get '/teaching_routes/update_routes/' => 'teaching_routes#update_routes'
  post '/teaching_routes/update_routes/' => 'teaching_routes#upload_file'
  match '/teaching_routes/update_names/' => 'teaching_routes#update_names'
  match '/teaching_routes/update_error/' => 'teaching_routes#update_error'
  post '/teaching_routes/update_with_path/' => 'teaching_routes#update_with_path'
  match '/teaching_routes/teacherList/:id' => 'teaching_routes#teacherList'

  get '/visiting_teaching' => 'visiting_teaching#index'
  get '/visiting_teaching/update_routes/' => 'visiting_teaching#update_routes'
  post '/visiting_teaching/update_routes/' => 'visiting_teaching#upload_file'
  post '/visiting_teaching/update_with_path/' => 'visiting_teaching#update_with_path'
  match '/visiting_teaching/update_names/' => 'visiting_teaching#update_names'
  match '/visiting_teaching/update_error/' => 'visiting_teaching#update_error'
  match '/visiting_teaching/teacher_list/' => 'visiting_teaching#teacher_list'

  match '/todo' => 'users#todo'
  resources :users, :only => [:index, :new, :create, :update, :destroy]

  match '/WardListUpdates' => 'people#WardListUpdates'
  resources :people

  resources :events
  resources :password_resets
  resources :roster
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions
  match '/families/members/' => 'families#members'
  match '/families/teachingPool/' => 'families#teachingPool'
  match '/families/investigators/' => 'families#investigators'
  match '/families/mergeRecords/' => 'families#mergeRecords'
  post '/families/:id/new_comment' => 'families#new_comment'
  match '/families/edit_status/:id' => 'families#edit_status'
  match '/activate/:id' => 'password_resets#activate', :as => :activation
  resources :families
  match '/' => 'families#index'
  match '/:controller(/:action(/:id))'

  resources :callings
  match '/callings/updateAccessLevels/' => 'callings#updateAccessLevels'

  resources :auth_users
  resources :teaching_records
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :family
  belongs_to :person


  attr_accessible :text, :person_id, :family_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

# TOOD probably want to make this more restrictive
  def checkAccess
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    if hasAccess(3) || (!@comment.person.nil? && @comment.person.id == session[:user_id])
      @comment.text = params[:text]
      @comment.save
    end

    redirect_to(@comment.family)
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    comment = Comment.find(params[:id])
    family = comment.family

    if hasAccess(3) || (!comment.person.nil? && comment.person.id == session[:user_id])
      comment.destroy
    end

    redirect_to(family)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% # TODO DRY fix with the access_level %>
<% if session[:access_level] >= 4 or (!comment.person.nil? and comment.person.id == session[:user_id]) %>
      <div id='comment_display_<%=comment.id%>' class='editable_comment'>
        <%= link_to_function simple_format(comment.text)[3..-5].html_safe, "switch_to_form('comment', #{comment.id})" %>
      </div>
      <%= form_tag comment_path(comment), :method => :put, :id => "comment_edit_form_#{comment.id}", :class => 'startHidden' do %>
        <%= text_area_tag :text, comment.text, :cols => 60, :rows => 5 %>
        <%= submit_tag "Update Info" %>
        <%= link_to_function "Cancel", "switch_back_from_form('comment', #{comment.id})" %>
      <% end %>
<% else %>
  <%= simple_format(comment.text)[3..-5].html_safe %>
<% end %>

<% unless comment.person == nil %>
  &mdash;<%= "#{comment.person.name} #{comment.person.family.name} #{comment.updated_at.strftime("%b %d, %y")}" %>
<% end %>

<% if session[:access_level] >= 4 or (!comment.person.nil? and comment.person.id == session[:user_id]) %>
  &nbsp;
  <%= button_to 'Delete', comment_path(comment), {:method => :delete} %>
<% end %>
<br>
<br>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_for(@comment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :family_id %><br />
    <%= f.text_field :family_id %>
  </p>
  <p>
    <%= f.label :person_id %><br />
    <%= f.text_field :person_id %>
  </p>
  <p>
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Family</th>
    <th>Person</th>
    <th>Text</th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%=h comment.family_id %></td>
    <td><%=h comment.person_id %></td>
    <td><%=h comment.text %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= form_for(@comment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :family_id %><br />
    <%= f.text_field :family_id %>
  </p>
  <p>
    <%= f.label :person_id %><br />
    <%= f.text_field :person_id %>
  </p>
  <p>
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <b>Family:</b>
  <%=h @comment.family_id %>
</p>

<p>
  <b>Person:</b>
  <%=h @comment.person_id %>
</p>

<p>
  <b>Text:</b>
  <%=h @comment.text %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>