config/routes.rb
WardAreaBook::Application.routes.draw do

  match '/faq' => 'static_pages#faq'

  match '/action_items/wardActionItems/' => 'action_items#wardActionItems'
  resources :action_items, :only => [:create, :update, :destroy]
  resources :comments, :only => [:update, :destroy]

  get '/teaching_routes' => 'teaching_routes#index'
  get '/teaching_routes/update_routes/' => 'teaching_routes#update_routes'
  post '/teaching_routes/update_routes/' => 'teaching_routes#upload_file'
  match '/teaching_routes/update_names/' => 'teaching_routes#update_names'
  match '/teaching_routes/update_error/' => 'teaching_routes#update_error'
  post '/teaching_routes/update_with_path/' => 'teaching_routes#update_with_path'
  match '/teaching_routes/teacherList/:id' => 'teaching_routes#teacherList'

  get '/visiting_teaching' => 'visiting_teaching#index'
  get '/visiting_teaching/update_routes/' => 'visiting_teaching#update_routes'
  post '/visiting_teaching/update_routes/' => 'visiting_teaching#upload_file'
  post '/visiting_teaching/update_with_path/' => 'visiting_teaching#update_with_path'
  match '/visiting_teaching/update_names/' => 'visiting_teaching#update_names'
  match '/visiting_teaching/update_error/' => 'visiting_teaching#update_error'
  match '/visiting_teaching/teacher_list/' => 'visiting_teaching#teacher_list'

  match '/todo' => 'users#todo'
  resources :users, :only => [:index, :new, :create, :update, :destroy]

  match '/WardListUpdates' => 'people#WardListUpdates'
  resources :people

  resources :events
  resources :password_resets
  resources :roster
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions
  match '/families/members/' => 'families#members'
  match '/families/teachingPool/' => 'families#teachingPool'
  match '/families/investigators/' => 'families#investigators'
  match '/families/mergeRecords/' => 'families#mergeRecords'
  post '/families/:id/new_comment' => 'families#new_comment'
  match '/families/edit_status/:id' => 'families#edit_status'
  match '/activate/:id' => 'password_resets#activate', :as => :activation
  resources :families
  match '/' => 'families#index'
  match '/:controller(/:action(/:id))'

  resources :callings
  match '/callings/updateAccessLevels/' => 'callings#updateAccessLevels'

  resources :auth_users
  resources :teaching_records
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_many :events, :order => 'date DESC, updated_at DESC', :dependent => :destroy
  has_many :people
  has_many :comments
  has_many :teaching_routes  # really it only has two
  has_many :home_teachers, :through => :teaching_routes, :source => :person
  has_many :action_items, :order => 'due_date DESC', :dependent => :destroy
  has_many :open_action_items, :class_name => "ActionItem",
                               :conditions => "status = 'open'",
                               :order => 'due_date ASC, updated_at DESC'
  has_many :closed_action_items, :class_name => "ActionItem",
                                 :conditions => "status = 'closed'",
                                 :order => 'updated_at DESC'
  has_one :teaching_record

  attr_accessible :status, :name, :head_of_house_hold, :phone, :address, :uid, :current

  validates_presence_of :name, :head_of_house_hold


  ALL = self.where("member = ? AND current = ?", true, true).order('name').map do |s|
    begin
    [s.name + ", " + s.head_of_house_hold, s.id]
    rescue
    end
  end

  def hasHomeTeacher(person_id)
    self.teaching_routes.each do |route|
      return true if route.person_id == person_id
    end
    return false
  rescue
    return false
  end

  def hasVisitingTeacher(person_id)
    self.people.includes(:visiting_teachers).each do |person|
      person.visiting_teachers.each do |vt|
        return true if vt.id == person_id
      end
    end
    return false
  rescue
    return false
  end

  def lastVisit
    self.events.where("category != 'Attempt' and
                            category != 'Other' and
                            category is not NULL").first
  end

  def mergeTo(familyRecord)
    #TODO append action items
    begin
      # Copy over the events
      self.events.each do |event|
        event.family_id = familyRecord.id
        event.save!
      end

      #copy over any teaching records
      if self.teaching_record
        self.teaching_record.family_id = familyRecord.id
        self.teaching_record.save!
      end

      # Append any append any infomation to the new record
      if self.information
        # TODO there's got to be a better way of doing this....
        if familyRecord.information
          familyRecord.information += "<br> " + self.information
        else
          familyRecord.information =  self.information
        end
        familyRecord.save!
      end

      # finally delete this record
      self.delete
    end
  end


  def self.visitedWithinTheLastMonths(monthsAgo)
    targetDate = Date.today.months_ago(monthsAgo).at_beginning_of_month
    return Family.order(:name).includes(:events)
        .where(:current => true, :member => true)
        .where(['status != ?', 'moved'])
        .where(['events.date >= ?', targetDate])
        .where(['events.category != ?', 'Attempt'])
        .where(['events.category != ?', 'Other'])
        .where('events.category is not NULL')
  end

  def full_name
    "#{self.head_of_house_hold} #{self.name}"
  end

  def self.get_families
    @families = Family.where('current = ?', true).order('name').map do |s|
      [s.name + "," + s.head_of_house_hold, s.id]
    end
  end

end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  #TODO for some reason the sweeper is not getting called when I update 
  #the family records.  So I instead I'm explicitly updating this.
  #the sweeper is working for the events_controller....
  in_place_edit_for :action_item, :action

  @hasFullAccess = false

  # override the application accessLevel method
  # TODO refactor this method
  def checkAccess
    @hasFullAccess = hasAccess(3)
    # Everybody has access to these methods
    if hasAccess(3) or 
       action_name == 'members' or 
       action_name == 'show' or 
       action_name == 'edit_status' or 
       (action_name == 'edit' and (Family.find(params[:id]).hasHomeTeacher(session[:user_id]) or @family.hasVisitingTeacher(session[:user_id]))) or 
       (action_name == 'update' and (Family.find(params[:id]).hasHomeTeacher(session[:user_id]) or @family.hasVisitingTeacher(session[:user_id])))
      true
    elsif
      action_name == 'index' and not hasAccess(3)
      redirect_to(:action => 'members')
    else
      deny_access
    end
  end

  # GET /families
  # GET /families.xml
  def index
    @families = Family.find_all_by_member_and_current(true,true, :order => :name)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @families }
    end
  end

  # This is a limited access list
  def members
    @families = Family.find_all_by_member_and_current(true,true, :order => :name)
    respond_to do |format|
      format.html # investigators.html.erb
      format.xml  { render :xml => @families }
    end
  end

  def new_comment
    @fam = Family.find(params[:id])
    @fam.comments.create(:person_id => session[:user_id], :text => params[:text])
    redirect_to(@fam)

  end

  def investigators
    @families = Family.find_all_by_member_and_current(false, true, :order => :name)
    respond_to do |format|
      format.html # investigators.html.erb
      format.xml  { render :xml => @families }
    end
  end

  def edit_status
    @edit_status = true
    show
  end

  def listArchived
    @families = Family.find_all_by_member_and_current(false, false, :order => :name)
    render :update do |page|
      page.replace_html("archived-families",
                   :partial => "droppedFamilies",
                   :object => @families)
    end
  end

  def mergeRecords
    @family = Family.find(params[:family])
    if @family.member
      redirect_to :back 
    else
      @familyList = Family.find_all_by_member_and_current(true,true)
      respond_to do |format|
        format.html # investigators.html.erb
        format.xml  { render :xml => @families }
      end
    end
  end

  def merge_the_record
    @family = Family.find(params[:family])
    @memberRecord = Family.find(params[:family_to_merge_with])
    @family.mergeTo(@memberRecord)
    respond_to do |format|
      format.html { redirect_to(@memberRecord) }
    end
  end


  # GET /families/1
  # GET /families/1.xml
  def show
    @family = Family.find(params[:id])
    @action_item = ActionItem.new
    @action_item.family_id = @family.id

    @names = Person.selectionList
    @families = Family.get_families

    @familyName = @family.name + "," + @family.head_of_house_hold;
    @fellowShippers = Person.selectionList

    @event =  Event.new
    @event.family_id = @family.id

    @limit = CLOSED_ACTION_LIMIT

    if @hasFullAccess or @family.hasHomeTeacher(session[:user_id]) or @family.hasVisitingTeacher(session[:user_id])
      render "show"
    else
      # TODO: This needs more work. There should probably be just one view, and it should be cleaned up
      user = Person.find(session[:user_id])
      @show_events = (@family.people.include? user) ? true : false
      render "show2"
    end
  end

  # GET /families/new
  # GET /families/new.xml
  def new
    @family = Family.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @family }
    end
  end

  # GET /families/1/edit
  def edit
    @family = Family.find(params[:id])
  end

  # POST /families
  # POST /families.xml
  def create
    @family = Family.new(params[:family])

    respond_to do |format|
      if @family.save
        flash[:notice] = 'Family was successfully created.'
        format.html { redirect_to(@family) }
        format.xml  { render :xml => @family, :status => :created, :location => @family }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @family.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /families/1
  # PUT /families/1.xml
  def update
    @family = Family.find(params[:id])
    begin
      if params[:family][:status] != @family.status
        @family.events.create(:date => Date.today, 
                              :person_id => session[:user_id],
                              :author => session[:user_id],
                              :comment => "Changed status from #{@family.status} 
                                           to #{params[:family][:status]}")
      end
    rescue
      logger.info("Caught an Exception")
    end
    respond_to do |format|
      if @family.update_attributes(params[:family])
        expire_action :action => "index"
        expire_action :action => "show", :id => @family
        #flash[:notice] = 'Family was successfully updated.'
        format.js {
          render :update do |page|
          page.replace_html("family_status", 
                            :partial => "family_status", 
                            :object => @family,
                            :locals => {:update => nil})
          end
        }
        format.html { redirect_to(@family) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @family.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.xml
  def destroy
    @family = Family.find(params[:id])
    @family.destroy

    respond_to do |format|
      format.html { redirect_to(:action => 'investigators') }
      format.xml  { head :ok }
    end
  end

  def archive 
    @family = Family.find(params[:id])
    if params[:restore] == 'true'
      @family.current = true
      if @family.teaching_record 
        @family.teaching_record.current = true
        @family.teaching_record.save
      end
    else
      @family.current = false
      if @family.teaching_record 
        @family.teaching_record.current = false
        @family.teaching_record.save
      end
    end
    @family.save
    respond_to do |format|
      format.html { redirect_to(:action => 'investigators') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/families_helper.rb
module FamiliesHelper
  def statusColor(status)
    case status
      when /dnc/i            ; "maroon"
      when /less active/i    ; "cyan"
      when /missionary/i    ; "cyan"
      when /active/i         ; "#00ff00"
      when /member/i         ; "#00ff00"
      when /mailing/i        ; "#B88A00"
      when /not interested/i ; "#B88A00"
      when /moved/i          ; "red"
      when /returned/i       ; "red"
      when /request/i       ; "red"
      when /investigator/i  ; "yellow"
      when /recent convert/i       ; "yellow"
      else ; "yellow"
    end
  end

  def displayAddress(address)
    begin
      # city, state zipcode   - put a break right before the city.
      zipcode_index = address.rindex(/\W+\w+\W+\w+\W+\d\d\d\d\d/)

      formatted_address = "".html_safe
      formatted_address << address[0..zipcode_index]
      formatted_address.safe_concat "<br />"
      formatted_address << address[zipcode_index..-1]
    rescue
      address
    end
  end

  def getLastVisitDate(family)
    lastVisit = family.lastVisit
    if lastVisit != nil
      lastVisit.date.to_s(:sortable)
    else
      ""
    end
  end

  def getLastVisitDateSortable(family)
    lastVisit = family.lastVisit
    if lastVisit != nil
      lastVisit.date.strftime("%Y%m%d")
    else
      ""
    end
  end
    

  def getLastVisitComment(family)
    lastVisit = family.lastVisit
    if lastVisit != nil
      truncate(lastVisit.comment, :length => 100) 
    else
      lastContact = family.events.first
      if lastContact != nil
        truncate(lastContact.comment, :length => 100) 
      else
        ""
      end
    end
  end

  def nonmemberType
    [
      ["Missionary Find" , "Missionary Find"],
      ["Member Referral" , "Member Referral"],
      ["Self Referral"   , "Self Referral"],
      ["Part Member"     , "Part Member"],
      ["Request Records" , "Request Records"]
    ]
  end
  def memberStatus
    [
      ["active"          , "active"], 
      ["less active"     , "less active"], 
      ["moved"           , "moved"], 
      ["not interested"  , "not interested"],
      ["dnc"             , "dnc" ]
    ]
  end
end

app/views/families/_droppedFamilies.html.erb
<a href='#' onclick="Effect.toggle('dropped-families', 'blind'); return false;">Dropped Families</a> 

<div id = 'dropped-families'>
  <h1>Dropped Families</h1>
  <%= render(:partial => 'list_families', :object => @families, :locals => {:dropped => true}) %> 
</div>

app/views/families/_family_details.html.erb
<li> 
  <a href='#' class = 'subtile-links' onclick="Effect.toggle('family-details', 'blind'); return false;">Family Details </a>
  <div id="family-details" class="family_details">
    <div>
      <table>
        <tr>
          <td >
            <b>Status:</b>
            <span id='family_status' class='editable_comment'>
              <%= render(:partial => "family_status", 
                         :object => @family, 
                         :locals => {:update => @edit_status}) %>
            </span>
          </td>
          <td ></td>
          <td ></td>
       </tr>
        <tr>
          <td > 
            <%= @family.head_of_house_hold %>
            <ul class='nodot'> <li>
              <% @family.people.each do |member| %>
                <% if member.current == true %>
                  <%= member.name -%> 
                  <% if member.email != nil %> 
                    &mdash; <%= member.email %>
                  <% end %>
                  <br>
                <% end %>
              <% end %> </li> 
            </ul>
          </td>
          <td > 
            <% if @family.phone != ""%>
              <%= @family.phone %><br><br>
            <% end %>
              <%= displayAddress(@family.address) %>
          </td>
          <td >
            <% if @family.teaching_routes.size == 0 %>
              <b>Home Teachers have not been <br />
                assigned to this family</b><br />
            <% else %>
              <% @family.teaching_routes.each do |teacher| %>
                Home Teacher: <%= teacher.person.name + " " + teacher.person.family.name %> <br />
              <% end %>
            <% end %>
            <% @family.people.each do |member| %>
              <% member.visiting_teachers.each do |vt| %>
                Visiting Teacher: <%= vt.name + " " + vt.family.name %> teaches <%= member.name %> <br />
              <% end %>
            <% end %>
          </td>
        </tr>
      </table>
      <h4>General Information:</h4> 
      <span id="comments">
        <%= render(:partial => "comments/comment", :collection => @family.comments) %>
      </span>

      <% unless @family.member %>
        <div class="noPrint">
          <%= link_to 'Edit family details', edit_family_path(@family) %><br>
          <br>
          <%= link_to 'Merge records', :controller => 'families', 
            :action => 'mergeRecords', 
            :family => @family %><br>
            <br><br>                                     
        </div>
      <% end %>

    </div>
  </div>
</li>

app/views/families/_family_status.html.erb
<% if update %>
    <%= form_for @family, :url => { :controller => "families", :action => "update", :id => @family} do |f| %>
    <%= f.error_messages %>
    <% if @family.member == false %>
      <%= f.select :status, nonmemberType %>
    <% else %> 
      <%= f.select :status, memberStatus %>
    <% end %>
    &nbsp;
    <%= f.submit 'Update' %>
    <%= link_to 'cancel', {:controller => "families", :action => "show", :id => @family.id}, {:style=>'text-decoration:underline'}%>
  <% end %>
<% else %>
  <span style='background-color: <%= statusColor(@family.status) -%>'>
    <%= link_to @family.status, :controller => "families", :action => "edit_status", :id => @family.id %>&nbsp;
  </span>
<% end %>

app/views/families/_list_families.html.erb
<% dropped ||= false %> 
<% header ||= false %> 
<% if header %>
  <h3> <%=header%></h3>
<% end %>
<% nonMember = nonMember || dropped || false %> 
<table id = 'filterable' class = 'sorttable resizable'>
  <thead>
    <tr align="left">
      <th>Name**</th>
      <th class='sorttable_nosort'>Phone</th>
      <th class='sorttable_nosort'>Address</th>
      <% if nonMember %>
      <th>Type**</th>
      <% else %>
      <th>Status**</th>
      <% end %>
      <th padding='10px'>Last&nbsp;Visit**</th>
      <th class='sorttable_nosort'>Comment</th>
      <% if nonMember %>
      <th class='sorttable_nosort'></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% list_families.each do |family| %>
      <tr class="<%=cycle('list-line-odd','list-line-even')%>" 
        onClick = "window.location.href='<%= family_path(family) %>'" >
        <td ><%=h family.name %>, <%=h family.head_of_house_hold %></td>
        <td ><%=h family.phone %></td>
        <td ><%=h family.address %></td>
        <td bgcolor=<%=statusColor(family.status)%>>
          <%=h family.status %></td>
        <td sorttable_customkey="<%=getLastVisitDateSortable(family)%>"> 
          <%= getLastVisitDate(family) %></td>
        <td ><%= getLastVisitComment(family) %></td>
        <% if nonMember %>
          <% if dropped %>
            <td><%= link_to 'Restore', 
              :controller=>'families', 
              :action => 'archive', 
              :id => family, 
              :restore => 'true'%> </td>
          <% else %>
            <td><%= link_to 'Drop', 
              :controller=>'families', 
              :action => 'archive', 
              :id => family %> </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/families/_submit_button.html.erb
<%= form_tag :url => {:controller => :comments, 
                            :action => 'new', 
                            :remote => true,
                            :id => @family.id } do %>
  <%= submit_tag "Add Info." %>
<% end %>

app/views/families/edit.html.erb
<h1>Editing family <%= @family.name %> </h1>

<%= form_for(@family) do |f| %>
  <%= f.error_messages %>

  <p>
    <% if @family.member == false %>
      Last Name:
      <%= f.text_field :name %>&nbsp;&nbsp;&nbsp; 
      Head Of Household: 
      <%= f.text_field :head_of_house_hold %> 
    <% else %>
      <%= @family.head_of_house_hold %>
    <% end %>
  </p>
  <p>
    <% if @family.member == false %>
      <%= f.label :phone %> 
      <%= f.text_field :phone %> &nbsp;&nbsp;&nbsp; 
      <%= f.label :address %> 
      <%= f.text_field :address %> 
    <% else %>
      <%= @family.phone %> &nbsp; &nbsp; &nbsp; 
      <%= @family.address %>
    <% end %>
  </p>
  <p>
    <%= f.label :status %><br />
    <% if @family.member == false %>
      <%= f.select :status, nonmemberType %>
    <% else %> 
      <%= f.select :status, memberStatus %>
    <% end %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

app/views/families/index.html.erb
<h1>Listing families </h1>
  <div style = "font:85% sans-serif;" >
    <form>
      Quick Search &mdash;
      <input name="quickSearch" onkeyup="filterTable(this, 'filterable', 0,3)" type="text">
    </form>
  </div>
  <br>
  <%= render :partial => "families/list_families", :object => @families %>

app/views/families/investigators.html.erb
<h1>Investigating families</h1>

<p>
  <%= link_to 'Create a new family', new_family_path %>
</p>

<div id = 'investigating-families'>
  <%= render(:partial => 'list_families', :object => @families, 
             :locals => {:nonMember => true}) %> 
</div>

<br /> <br /> <br />
<div id='archived-families'>
  <%= link_to "Dropped Families", :url => {:controller => "families",  :action => 'listArchived'}, :remote => true %>
</div>

app/views/families/members.html.erb
<h1>Listing families</h1>

<table class = 'sortable resizable'>
  <thead>
  <tr align="left">
    <th>Name**</th>
    <th class='nosort'>Phone</th>
    <th class='nosort'>Address</th>
  </tr>
</thead>
<tbody>

<% @families.each do |family| %>
  <tr class="<%=cycle('list-line-odd','list-line-even')%>" 
    onClick = "window.location.href='<%= family_path(family) %>'" >
    <td><%=h family.name %>, <%=h family.head_of_house_hold %></td>
    <td><%=h family.phone %></td>
    <td><%=h family.address %></td>
  </tr>
<% end %>
</tbody>
</table>
<br />
<br />
<br />

app/views/families/mergeRecords.html.erb
<h1>Merge records for familiy <%= @family.name %> </h1>

<%= form_tag(:action => :merge_the_record) do  %>
  <p>
    This options allows you to transfer all events and teaching records<br> 
    from this 'non-member' record to an official member record from the ward list.
  </p>
  <p>
    It's pretty hard to undo this so be sure to select the correct family...
  </p>
  <br><br>
  <p>
    Merge Records for:
    <%= @family.head_of_house_hold %> <%= @family.name %> with 
    <%= hidden_field_tag 'family', @family.id %>
    <%= select_tag 'family_to_merge_with', options_for_select(Family::ALL) %>
 </p>
  <br>
  <p>
    <%= submit_tag 'Merge', :confirm => "This operation will remove record " + 
                                          @family.name + '   Are you sure?' %>
    <%= link_to 'Cancel', family_path(@family) %>
  </p>
<% end %>

app/views/families/new.html.erb
<h1>New family</h1>

<%= form_for(@family) do |f| %>
  <%= f.error_messages %>

  <table style="border-style:hidden">
    <tr>
      <td>
        <%= f.label :head_of_house_hold %><br />
        <%= f.text_field :head_of_house_hold %>
      </td>
      <td>
        <%= f.label "Last Name" %><br />
        <%= f.text_field :name %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :phone %><br />
        <%= f.text_field :phone %>
      </td>
      <td>
        <%= f.label :address %><br />
        <%= f.text_field :address %>
      </td>
    </tr>
  </table>
  <p>
  </p>
  <p>
    <%= f.label "Type" %><br />
    <%= f.select :status, nonmemberType %>
    </p>
    <!-- TODO field for comments -->
    <%= f.hidden_field :member, :value => 0 %>
    <%= f.submit 'Create' %>
    <%= link_to 'Cancel', 'investigators' %>
  <% end %>

app/views/families/show.html.erb
<h1><%= @family.name %> Family &nbsp;&nbsp;&nbsp;&nbsp;
  <div id='actionButtons' >
    <%= button_to_function("New Visit", "$('#new-event').show(); $('#actionButtons').hide();")%>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     
    <%= button_to_function("New Action Item", "$('#new-action').show(); $('#actionButtons').hide();")%>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     
    <%= button_to_function("New Family Info", "$('#new-comment').show(); $('#actionButtons').hide();")%>
  </div>
</h1>

<div id='new-event' style='display:none;'> 
  <%= render(:partial => 'events/new_family_event',
             :locals => {:peopleList => @names,
                         :event => @event,
                         :family => @family}) %>
   <%= render(:partial => 'shared/leadership_emails') %>
  <hr>
</div>

<div id='new-action' style='display:none;'> 
  <%= render(:partial => 'action_items/new_family_action_item', 
             :locals => {:peopleList => @names,
                         :action_item => @action_item}) %>
  <%= render(:partial => 'shared/leadership_emails') %>
  <hr>
</div>

<div id="new-comment" class="startHidden">
  <%= form_tag family_path(@family) + '/new_comment', :class => "noPrint" do %>
    <%= text_area_tag :text, nil, :cols => 60, :rows => 5 %><br />
    <%= submit_tag "Add Info" %>
    <%= link_to_function "Cancel", "$('#new-comment').hide(); $('#actionButtons').show();" %>
  <% end %>
  <%= render(:partial => 'shared/leadership_emails') %>
  <hr>
</div>
<ul>
    <%= render(:partial => "family_details") %>
    <%= render(:partial => "teaching_records/teaching_record",
               :object => @family.teaching_record,
               :locals => {:events => @family.events}) %>
               <%= render(:partial => "events/family_events", :locals => {:names => @names}) %>
    <div id="updated-action-list">
      <%= render(:partial => "action_items/family_action_items",
                 :locals => {:option_for_more => true}) %>
    </div>
</ul>

app/views/families/show2.html.erb
<h1><%= @family.name %> Family &nbsp;&nbsp;&nbsp;&nbsp; </h1>
  <!-- Family Details -->
    <table style='border:none'>
      <tr>
        <td style='border:none'>
          <%= @family.head_of_house_hold %>
          <ul id='nodot'>
            <li>
              <% @family.people.each do |member| %>
                <% if member.current == true %>
                  <%= member.name -%> 
                  <% if member.email != nil %> 
                    &mdash; <%= member.email %>
                  <% end %>
                  <br>
                <% end %>
              <% end %>
            </li>
          </ul>
        </td>
        <td style='border:none'>&nbsp;&nbsp;&nbsp;</td>
        <td style='border:none'>
          <%= @family.phone %><br>
          <p>
            <%= displayAddress(@family.address) %><br>
          </p>
        </td>
        <td style='border:none'>&nbsp;&nbsp;&nbsp;</td>
        <td style='border:none'> 
          <% @family.teaching_routes.each do |teacher| %>
            Home Teacher: <%= teacher.person.name + " " + teacher.person.family.name %> <br>
          <% end %>
          <% @family.people.each do |member| %>
            <% member.visiting_teachers.each do |vt| %>
              Visiting Teacher: <%= vt.name + " " + vt.family.name %> teaches <%= member.name %> <br />
            <% end %>
          <% end %>
        </td>
      </tr>
    </table>
    <% if @show_events %>
    <%= render(:partial => "teaching_records/teaching_record",
               :object => @family.teaching_record,
               :locals => {:events => @family.events}) %>
               <%= render(:partial => "events/family_events", :locals => {:names => @names}) %>
 
    <% end %>
<br> <br> <br>
<br> <br> <br>
<br> <br> <br>

app/views/families/teachingPool.html.erb
<h1>Ward Teaching Pool</h1>

<table class = 'sortable resizable'>
  <thead>
  <tr align="left">
    <th>Name**</th>
    <th class='nosort'>Type</th>
    <th class='nosort'>Lessons Taught</th>
    <th>Type**</th>
    <th padding='10px'>Last&nbsp;Visit**</th>
    <th padding='10px'>Next&nbsp;Visit**</th>
    <th class='nosort'>Fellowshipper</th>
    <th class='nosort'></th>
  </tr>
</thead>
<tbody>

<% @families.each do |family| %>
  <tr class="<%=cycle('list-line-odd','list-line-even')%>">
    <td onClick = "window.location.href='<%= family_path(family) %>'" ><%=h family.name %>, <%=h family.head_of_house_hold %></td>
    <td onClick = "window.location.href='<%= family_path(family) %>'" ><%=h family.phone %></td>
    <td onClick = "window.location.href='<%= family_path(family) %>'" ><%=h family.address %></td>
    <td onClick = "window.location.href='<%= family_path(family) %>'" ><%=h family.status %></td>
    <td onClick = "window.location.href='<%= family_path(family) %>'" sorttable_customkey="<%=getLastVisitDateSortable(family)%>"> <%= getLastVisitDate(family) %></td>
    <td onClick = "window.location.href='<%= family_path(family) %>'" ><%= getLastVisitComment(family) %></td>
    <td><%= link_to 'remove', family, :confirm => 'Are you sure?', :method => :removeFromTeachingPool %></td>
  </tr>

<% end %>
</tbody>
</table>

<br />
<br />
<%= link_to 'Add Family', :action => :addToTeachingPool %>