config/routes.rb
WardAreaBook::Application.routes.draw do

  match '/faq' => 'static_pages#faq'

  match '/action_items/wardActionItems/' => 'action_items#wardActionItems'
  resources :action_items, :only => [:create, :update, :destroy]
  resources :comments, :only => [:update, :destroy]

  get '/teaching_routes' => 'teaching_routes#index'
  get '/teaching_routes/update_routes/' => 'teaching_routes#update_routes'
  post '/teaching_routes/update_routes/' => 'teaching_routes#upload_file'
  match '/teaching_routes/update_names/' => 'teaching_routes#update_names'
  match '/teaching_routes/update_error/' => 'teaching_routes#update_error'
  post '/teaching_routes/update_with_path/' => 'teaching_routes#update_with_path'
  match '/teaching_routes/teacherList/:id' => 'teaching_routes#teacherList'

  get '/visiting_teaching' => 'visiting_teaching#index'
  get '/visiting_teaching/update_routes/' => 'visiting_teaching#update_routes'
  post '/visiting_teaching/update_routes/' => 'visiting_teaching#upload_file'
  post '/visiting_teaching/update_with_path/' => 'visiting_teaching#update_with_path'
  match '/visiting_teaching/update_names/' => 'visiting_teaching#update_names'
  match '/visiting_teaching/update_error/' => 'visiting_teaching#update_error'
  match '/visiting_teaching/teacher_list/' => 'visiting_teaching#teacher_list'

  match '/todo' => 'users#todo'
  resources :users, :only => [:index, :new, :create, :update, :destroy]

  match '/WardListUpdates' => 'people#WardListUpdates'
  resources :people

  resources :events
  resources :password_resets
  resources :roster
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions
  match '/families/members/' => 'families#members'
  match '/families/teachingPool/' => 'families#teachingPool'
  match '/families/investigators/' => 'families#investigators'
  match '/families/mergeRecords/' => 'families#mergeRecords'
  post '/families/:id/new_comment' => 'families#new_comment'
  match '/families/edit_status/:id' => 'families#edit_status'
  match '/activate/:id' => 'password_resets#activate', :as => :activation
  resources :families
  match '/' => 'families#index'
  match '/:controller(/:action(/:id))'

  resources :callings
  match '/callings/updateAccessLevels/' => 'callings#updateAccessLevels'

  resources :auth_users
  resources :teaching_records
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :family;
  belongs_to :person;

  attr_accessible :date, :family_id, :person_id, :category, :comment

  validates_presence_of :family_id

  include TeachingRecordsHelper

  def getCategory
    if memberMilestones.include?([self.category,self.category])
      "Milestone"
    elsif self.category == "Attend Church"
      "Attend<br>Church"
    else
      self.category
    end
  end

  def getComment
    wardRep = ""
    if self.person
      wardRep = self.person.full_name
    end
    if memberMilestones.include?([self.category,self.category])
      "#{wardRep} &ndash #{self.category}.  #{self.comment}"
    elsif self.comment and self.comment.size > 0
      "#{wardRep} &ndash #{self.comment}" 
    else
      "#{wardRep}" 
    end
  end

  def getHomeTeachers
    homeTeachers = Array.new
    if self.family.teaching_routes.size == 0
      # TODO get this more explicitly
      
      homeTeachers << Calling.find_by_job("Elders Quorum President")
      homeTeachers << Calling.find_by_job("High Priest Group Leader")
    else
      self.family.teaching_routes.each do |route|
        homeTeachers << route.person
      end
    end
    homeTeachers
  end

  def getEventDisplay
    if self.person 
      wardRep = self.person.full_name + " -- "
    else
      wardRep = ""
    end
    "#{self.date} -- #{wardRep}#{self.category} -- #{self.comment}"
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout 'admin'

# TOOD probably want to make this more restrictive
  def checkAccess
  end

  def edit_remotely
    @event = Event.find(params[:id])
    render :update do |page|
      page.replace_html("event_#{@event.id}", 
                        :partial => "events/event_edit", 
                        :object => @event)
    end
  end

  def update_remotely
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        #flash[:notice] = 'Event was successfully updated.'
        format.html { redirect_back }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /events
  # GET /events.xml
  def index
    if hasAccess(4)
      @events = Event.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @events }
      end
    else
      deny_access
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    render :layout => 'WardAreaBook'
  end

  

  def create_new_family_event
    @event = Event.new(params[:event])
    @event.author = session[:user_id]

    respond_to do |format|
      if @event.save
        #Advance the next milestone if: 
        #    the event is a memberMilestone 
        #    user has a teaching record
        #    this event is the current milestone
        if @template.memberMilestones.include?([@event.category,@event.category]) and 
            @event.family.teaching_record and 
            @event.category == @event.family.teaching_record.membership_milestone
          nextMileStone = @template.getNextMileStone(@event.family)
          @event.family.teaching_record.membership_milestone = nextMileStone[0]
          @event.family.teaching_record.save!
        end
        #flash[:notice] = 'Event was successfully created.'
        format.html { redirect_to(:controller => 'families', 
                                  :action => 'show', :id => @event.family_id)}
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])
    @event.author = session[:user_id]

    respond_to do |format|
      if @event.save
        #flash[:notice] = 'Event was successfully created.'
        format.html { redirect_to(@event) }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    event = Event.find(params[:id])
    if event.author == session[:user_id] or event.person_id == session[:user_id] or hasAccess(3)
      event.update_attributes(params[:event])
    end

    if params[:redirect] == "list"
      redirect_to events_path
    else
      redirect_to event.family
    end
  end

  #TODO Hack!  There's got to be a more approprate way to do this.
  def remove
    destroy
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    #flash[:notice] = 'Event successfully deleted.'
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_path }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def eventCategories 
    [
      ["Home Teaching"  , "Home Teaching"], 
      ["Visiting Teaching"  , "Visiting Teaching"], 
      ["Attempt", "Attempt"],
      ["Other", "Other"]
    ]
  end

  def getNextMileStone(family)
    memberMilestones.each do |milestone|
      if family.events.find_by_category(milestone[0])
        next
      else
        return milestone unless milestone[0] == "Baptized" and family.member
      end
    end
  end

  def getEvents(family)
    if family.teaching_record and family.teaching_record.current
      teachingRecordEvents + memberMilestones
    else
      eventCategories
    end
  end

end

app/views/events/_event.html.erb
<%
#=================== Set Up ============================
editable ||= true
hasAccessToEdit =false
isEditable = ""

# Can the user edit this action?

if editable and (event.author == session[:user_id] or event.person_id == session[:user_id]) 
  isEditable = "editable-action"
  hasAccessToEdit = true;
end
  
#=================== Partial Content ============================
%>
<div id = "event_<%=event.id%>"> 

  <% # Setup the display %>
  <div id="event_display_<%= event.id %>" class='<%=isEditable%>'>
    <% if hasAccessToEdit %>
      <%= link_to_function event.getEventDisplay, "switch_to_form('event', #{event.id})"%>
    <% else %>
      <%= event.getEventDisplay %>
    <% end %>
  </div>

  <% # Setting up the edit form, if they have access to edit %>
  <% if hasAccessToEdit %>
    <%= form_for event, :method => :put, :html => {:id => "event_edit_form_#{event.id}", :class => 'startHidden'} do |f|%>
      <p>
        <%= f.label :date %><br />
        <%= f.date_select :date %>
        <%= label_tag "Visiting Person" %>
        <%= f.select :person_id, options_for_select(names, event.person.id) %> <br />
      </p>
      <p>
      <% if event.family.teaching_record != nil %>
        <%= label_tag :category %>
        <%= f.select :category, options_for_select(teachingRecordEvents + memberMilestones, event.category) %>
      <% else %>
        <%= label_tag :category %>
        <%= f.select :category, options_for_select(eventCategories, event.category) %>
      <% end %>
      </p>
      <p>
        <%= label_tag :comment %><br />
        <%= f.text_area :comment, :cols => 75, :rows => 3 %>
      </p>
        <%= f.submit "Update Event" %>
        <%= link_to_function "Cancel", "switch_back_from_form('event', #{event.id})" %>
    <% end %>
  <% end %>
</div>

app/views/events/_event_edit.html.erb
<% peopleList ||= nil %>
<% familyList ||= nil %>
<% showFamily ||= false %>

<fieldset class='teaching-record'>
  <legend> Edit Event Item </legend>
  <%= form_for(event_edit, :url => {:controller => 'events', 
              :action => 'update_remotely', :id => event_edit.id })  do |f| %>
    <%= f.error_messages %>
    <p>
    Date: <%= f.date_select :date %>
    </p>
    <p>
      Ward Rep: <%= f.select :person_id, Person.selectionList, :include_blank => true %> 
      <% if showFamily %>
        <p>
          Family: <%= f.select :family_id, Family.get_families %> <br>
        </p>
      <% end %>
    </p>
    <p>
      Category: <%= f.select :category, getEvents(event_edit.family) %> <br>
    </p>
    
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :cols=>60,:rows=>2 %>
  </p>
  Author:<%= Person.find(@event.author).full_name %><br>
    <%= f.submit "update" %> &nbsp; &nbsp;
    <%= link_to "Cancel", "" %>
    <% if event_edit.author == session[:user_id] %>
      <%= button_to 'Delete', event_path(event_edit), :method => :delete %>
    <% end %>
  <% end %>
</fieldset>

app/views/events/_event_table.html.erb
<% #=================== Set Up ============================  -%>
<% editable ||= true %>
<% hasAccessToEdit =false %>
<% isEditable = "" %>

<% # Can the user edit this action?  -%>
<% if editable and (event_table.author == session[:user_id] or 
                    event_table.person_id == session[:user_id]) 
  isEditable = "editable"
  hasAccessToEdit = true;
end %>

<% options = {:url => {:controller => 'events',
                      :action => 'edit_remotely',
                      :id => event_table.id }} %>

<% #=================== Partial Content ============================  -%>
<div id="event_<%=event_table.id%>" >
<% if hasAccessToEdit %>
  <tr class="<%=isEditable%>" onclick="<%= remote_function(options) %>">
<% else %>
  <tr>
<% end %>
  <td> <%=h event_table.date %> </td>
  <td>&mdash;</td>
  <td> <%= event_table.getCategory %> </td>
  <td class='comment'>
    <%= event_table.getComment %>
  </td>
</tr>
</div>

app/views/events/_family_events.html.erb
<% unless @family.events().empty? %>
  <section id="events">
    <h3>Events</h3>

    <ul>
      <% @family.events.each do |event| %>
        <li>
          <%= render(:partial => "events/event", :object => event, :locals => {:names => names}) %>
        </li>
      <% end %>
    </ul>

  </section>
<% end %>

app/views/events/_lesson_event.html.erb
<% mileStoneEvent ||= false %>

<li id='nodot'>
  <% unless mileStoneEvent %>
    Taught by:
    <%=h lesson_event.person.name%>&nbsp;
    <%=h lesson_event.person.family.name%>&#151;
  <% end %>
  <%=h lesson_event.comment %>
  <% if mileStoneEvent %>
    &mdash;
    <%=h Person.find(lesson_event.author).name%>&nbsp;
    <%=h Person.find(lesson_event.author).family.name%>&#151;
  <% end %>
  <% if lesson_event.author == session[:user_id] or lesson_event.person_id == session[:user_id] %>
    <%= link_to 'Edit',   :controller => 'events', :action => 'edit', :id=> lesson_event %>
    <%= button_to 'Delete', event_path(lesson_event), :method => :delete %>
  <% end %>
</li>

app/views/events/_new_event.html.erb
<% form_for(@event, :url => {:action => 'create_new_family_event'})  do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :date %><br />
    <%= f.date_select :date %>
    <%= f.hidden_field :family_id %>
    Visiting Person
    <%= f.select :person_id, @names, {:selected => session[:user_id]} %> <br />
  </p>
  <p>
  <% if @family.teaching_record != nil %>
    <%= f.label :category %>
    <%= f.select :category, teachingRecordEvents %>
  <% else %>
    <%= f.label :category %>
    <%= f.select :category, eventCategories %>
  <% end %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :cols => 75, :rows => 3%>
  </p>
  <p>
    <%= f.submit 'Create' %>
    &nbsp; &nbsp; 
    <%= link_to 'Cancel', family_path(@family) %>
  </p>
<% end %>

app/views/events/_new_family_event.html.erb
<% peopleList ||= nil %>
<% event ||= nil %>
<% family ||= nil %>

<%= form_for(event, :url => {:controller => 'events', 
                            :action     => 'create_new_family_event'})  do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :date %><br />
    <%= f.date_select :date %>
    <%= f.hidden_field :family_id %>
    Visiting Person
    <%= f.select :person_id, peopleList, {:selected => session[:user_id]} %> <br />
  </p>
  <p>
  <% if family.teaching_record != nil %>
    <%= f.label :category %>
    <%= f.select :category, teachingRecordEvents + memberMilestones %>
  <% else %>
    <%= f.label :category %>
    <%= f.select :category, eventCategories %>
  <% end %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :cols => 75, :rows => 3%>
  </p>
  <p>
    <%= f.submit 'Create' %>
    &nbsp; &nbsp; 
    <%= link_to_function 'Cancel', "$('#new-event').hide(); $('#actionButtons').show();" %>
  </p>
<% end %>

app/views/events/_new_lesson_event.html.erb
<% peopleList ||= nil %>
<% event ||= nil %>
<% family ||= nil %>
<% mileStoneEvent ||= false %>

<%= form_for(event, :url => {:controller => 'events', 
                            :action     => 'create_new_family_event'})  do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :date %><br />
    <%= f.date_select :date %>
    <%= f.hidden_field :family_id %>
    <%= f.hidden_field :category %>
    <% unless mileStoneEvent %>
      Taught by
      <%= f.select :person_id, peopleList, {:selected => session[:user_id]} %> <br />
    <% end %>
  </p>
  <p>
    <% if mileStoneEvent %>
      Comments: <br>
    <% else %>
      Comments, committments given, fellowshipppers present? <br>
    <% end %>
    <%= f.text_area :comment, :cols => 55, :rows => 2%>
  </p>
  <p>
    <%= f.submit 'Create' %>
    &nbsp; &nbsp; 
    <% #TODO IT would be better to just collapse the window instead of reloading the page.  Other changes might get lost. %>
    <% if family.name == nil %>
      <% linkTo = "" %>
    <% else %>
      <% linkTo = family_path(family) %>
    <% end %>
    <%= link_to 'Cancel', linkTo %>
  </p>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= form_for(@event) do |f| %>
  <%= f.error_messages %>
  <%= hidden_field_tag :redirect, "list" %>

  <p>
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </p>
  <p>
  <%= @event.family.name %> Family (<%= @event.family.head_of_house_hold %>)
  </p>
  <p>
    <%= f.label :category %><br />
    <%= f.select :category, teachingRecordEvents + memberMilestones %>
  </p>
  <p>
    <%= f.label :person_id %><br />
    <%= f.select :person_id, Person.selectionList,
                 :prompt => "Select Visiting Member" %>
    
  </p>
  <p>
    <% author = Person.find(@event.author) %>
    <%= "Event created by: " + author.full_name %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :rows=>5 %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table class = 'sortable resizeable'>
  <thead>
  <tr align='left'>
    <th>Date</th>
    <th>Family</th>
    <th>Ward Representative</th>
    <th>Comment</th>
    <th class='nosort'>&nbsp;</th>
    <th class='nosort'>&nbsp;</th>
    <th class='nosort'>&nbsp;</th>
  </tr>
  </thead>

<% @events.each do |event| %>
  <tr>
    <td><%=h event.date %></td>
    <td><%=h event.family.name %></td>
    <% if event.person %>
      <td><%=h event.person.full_name %></td>
    <% else %>
      <td></td>
    <% end %>
    <td><%=h event.comment %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= button_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= form_for(@event) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </p>
  <p>
    <%= f.label :family_id %><br />
    <%= f.text_field :family_id %>
  </p>
  <p>
    <%= f.label :person_id %><br />
    <%= f.text_field :person_id %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
<b>Family:</b>
  <%= link_to(@event.family.name, @event.family) %>
</p>

<p>
<b>Visiting Member:</b>
  <% person = @event.person %>
  <%= person.nil? ? "No visitor specified" : link_to(person.full_name, person) %>
</p>

<p>
  <b>Comment:</b>
  <%= @event.comment %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>