config/routes.rb
WardAreaBook::Application.routes.draw do

  match '/faq' => 'static_pages#faq'

  match '/action_items/wardActionItems/' => 'action_items#wardActionItems'
  resources :action_items, :only => [:create, :update, :destroy]
  resources :comments, :only => [:update, :destroy]

  get '/teaching_routes' => 'teaching_routes#index'
  get '/teaching_routes/update_routes/' => 'teaching_routes#update_routes'
  post '/teaching_routes/update_routes/' => 'teaching_routes#upload_file'
  match '/teaching_routes/update_names/' => 'teaching_routes#update_names'
  match '/teaching_routes/update_error/' => 'teaching_routes#update_error'
  post '/teaching_routes/update_with_path/' => 'teaching_routes#update_with_path'
  match '/teaching_routes/teacherList/:id' => 'teaching_routes#teacherList'

  get '/visiting_teaching' => 'visiting_teaching#index'
  get '/visiting_teaching/update_routes/' => 'visiting_teaching#update_routes'
  post '/visiting_teaching/update_routes/' => 'visiting_teaching#upload_file'
  post '/visiting_teaching/update_with_path/' => 'visiting_teaching#update_with_path'
  match '/visiting_teaching/update_names/' => 'visiting_teaching#update_names'
  match '/visiting_teaching/update_error/' => 'visiting_teaching#update_error'
  match '/visiting_teaching/teacher_list/' => 'visiting_teaching#teacher_list'

  match '/todo' => 'users#todo'
  resources :users, :only => [:index, :new, :create, :update, :destroy]

  match '/WardListUpdates' => 'people#WardListUpdates'
  resources :people

  resources :events
  resources :password_resets
  resources :roster
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions
  match '/families/members/' => 'families#members'
  match '/families/teachingPool/' => 'families#teachingPool'
  match '/families/investigators/' => 'families#investigators'
  match '/families/mergeRecords/' => 'families#mergeRecords'
  post '/families/:id/new_comment' => 'families#new_comment'
  match '/families/edit_status/:id' => 'families#edit_status'
  match '/activate/:id' => 'password_resets#activate', :as => :activation
  resources :families
  match '/' => 'families#index'
  match '/:controller(/:action(/:id))'

  resources :callings
  match '/callings/updateAccessLevels/' => 'callings#updateAccessLevels'

  resources :auth_users
  resources :teaching_records
end

app/models/action_item.rb
class ActionItem < ActiveRecord::Base
  belongs_to :family
  belongs_to :person
  belongs_to :issuer, :class_name => "Person"

  attr_accessible :person_id, :family_id, :action, :due_date, :status, :comment

  validates_presence_of :person


  #TODO: Remove this method; I've added an 'issuer' association that gives a Person object rather than just the name, but I'm leaving this method as is for now so I don't break code somewhere else
  def author
    Person.find(self.issuer_id).full_name
  end
end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  listLimit = 5

  def checkAccess
    if (action_name == 'wardActionItems')
      if hasAccess(3)
        true
      else
        deny_access
      end
    else
      true
    end
  end


  def list_closed_action_items 
    condition = params[:conditions]
    @closed_action_items = ActionItem.find_all_by_status("closed", 
                                                         :conditions=>condition,
                                                         :order => 'updated_at DESC')
    render :update do |page|
      page.replace_html('closed-actions', 
                        :partial => "action_items/action_items", 
                        :object => @closed_action_items,
                        :locals => {:checkbox => true,
                                    :editable => true,
                                    # if condition is nil then this is for the ward action
                                    # page and I do want to show the family
                                    :family => (condition == nil),
                                    :ward_representative => true})
    end
  end

  def wardActionItems 
    @open_action_items   = ActionItem.find_all_by_status("open", :order => 'person_id, due_date ASC, updated_at DESC' )
    @person_actions = @open_action_items.group_by { |assignee| assignee.person } 
    

    @closed_action_items = ActionItem.find_all_by_status("closed", 
                                                         :conditions => ['updated_at > ?',1.week.ago], 
                                                         :order => 'updated_at DESC')

    @new_action_item = ActionItem.new
    @names = Person.selectionList
    @families = Family.get_families
    @limit = CLOSED_ACTION_LIMIT
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @action_items }
    end
  end

  # POST /action_items
  # POST /action_items.xml
  def create
    # TODO We need some access check on this
    @action_item = ActionItem.new(params[:action_item])
    @action_item.issuer = Person.find(session[:user_id])
    @action_item.status = "open"
    @action_item.save

    if params[:redirect] == "ward"
      redirect_to action_items_wardActionItems_path
    else
      redirect_to @action_item.family
    end
  end

  # PUT /action_items/1
  # PUT /action_items/1.xml
  def update
    # TODO We need some access check on this
    @action_item = ActionItem.find(params[:id])
    @action_item.update_attributes(params[:action_item])
    if params[:redirect] == "ward"
      redirect_to action_items_wardActionItems_path
    else
      redirect_to @action_item.family
    end
  end

  # DELETE /action_items/1
  # DELETE /action_items/1.xml
  def destroy
    # TODO We need some access check on this
    @action_item = ActionItem.find(params[:id])
    family = @action_item.family
    @action_item.destroy

    if params[:redirect] == "ward"
      redirect_to action_items_wardActionItems_path
    else
      redirect_to family
    end
  end
end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/views/action_items/_action_details.html.erb
<% #=================== Set Up ============================  -%>
<% ward_representative ||= false %>
<% noLinks ||= false %>
<% family   ||=false %>
<% showRequestor ||=false %>
<% isLate = "" %>
<% isClosed = "open-actions" %>

<% # Is the action late? %>
<% if (action_details.due_date < Date.today and 
       action_details.status == 'open')
       isLate = "late" 
end %>

<% # Is the action completed? %>
<% if action_details.status == 'closed'
  isClosed = "closed-actions" 
end %>

<% #=================== Code Content ============================  -%>

<% if ward_representative %>
  <% if noLinks %>
    <%= "#{action_details.person.full_name}" %> &#151; 
  <% else %>
    <%= link_to "#{action_details.person.full_name}", 
              {:controller =>'users', :action => 'todo', :id => action_details.person.id}, 
              :class=>"subtile-links" %> &#151;
  <% end %>
<% end %> 

<div class = '<%= isClosed %> <%= isLate %>'>
  <% if family and action_details.family%>
    <% if noLinks %>
      <%= "#{action_details.family.head_of_house_hold} #{action_details.family.name}" %> &#151; 
    <% else %>
      <%= link_to "#{action_details.family.head_of_house_hold} #{action_details.family.name}",
        family_path(action_details.family), :class=>"subtile-links" %> &#151;
    <% end %> 
  <% end %> 

  <div>
      <%=h "#{action_details.action} (#{action_details.due_date})" %>
    <% if showRequestor %>
      &ndash; requested by: <%= action_details.author %>
    <% end %>
  </div>
</div> <!-- IsClosed (strike through) isLate (red)-->

<div id = 'action-item-comment-<%= action_details.id %>'> 
  <% if action_details.comment && action_details.comment.size > 0 %>
    &nbsp;&nbsp;(<%=h action_details.comment %>)
  <% end %>
</div> <!-- Action Comment -->

app/views/action_items/_action_item.html.erb
<%
    checkbox ||= false
    form_action ||= "save_family_action"

    ward_representative ||= false
    family   ||=false
    editable ||=false
    noLinks  ||=false
    showRequestor ||=false
    hasAccessToEdit ||= false


    # Can the user edit this action?
    if editable and (action_item.issuer_id == session[:user_id] or action_item.person_id == session[:user_id])
     hasAccessToEdit = true
    end
%>

<div id = 'action_<%= action_item.id %>' class = 'action_item'>
  <% if checkbox %>
      <%= form_for action_item, :url => url_for(action_item), :method => :put do |f| %>
      <%= f.check_box(:status, 
                     {:onclick => "$('#action-item-edit-#{action_item.id}').toggle(); 
                                   $('#action-item-comment-#{action_item.id}').toggle();
                                   return true;"}, 
                    'closed', 'open') %>
      <%= render(:partial => 'action_items/action_details', 
                 :object => action_item,
                 :locals => {:ward_representative => ward_representative,
                             :editable => editable,
                             :showRequestor => showRequestor,
                             :noLinks => noLinks,
                             :family => family}) -%>

      <div id ='action-item-edit-<%= action_item.id %>' style='display:none; text-indent: 1.5em' class = 'comment'>
        <%= f.text_area(:comment, :rows=> 1) %>
        <%= f.submit "save" %> &nbsp;&nbsp;
        <%= link_to 'Cancel' %>

      </div>
    <% end %> <!-- end of the form above -->
  <% else %>  <!-- if 'not' checkbox -->
    <%= render(:partial => 'action_items/action_details', 
               :object => action_item,
               :locals => {:ward_representative => ward_representative,
                           :editable => editable,
                           :showRequestor => showRequestor,
                           :noLinks => noLinks,
                           :family => family}) %>
  <% end %>

  <% if hasAccessToEdit %>
      <%= button_to "Delete", action_item, :method => :delete %>
  <% end %>
</div>

app/views/action_items/_action_items.html.erb
<% option_for_more ||= false %>
<% conditions ||= nil %>

<% checkbox ||= false %>
<% form_action ||= false %>
<% ward_representative ||= false %>
<% family   ||=false %>
<% noLinks  ||=false %>
<% editable ||=false %>
<% showRequestor ||=false %>
<% style ||="id='nodot'" %>

<% #TODO I need to define some globals %>

<% action_items.each do |action| %>
  <li <%=style%>>
    <%= render(:partial => 'action_items/action_item', :object => action,
               :locals => {:checkbox => checkbox,
                           :form_action => form_action,
                           :showRequestor => showRequestor,
                           :ward_representative => ward_representative,
                           :family => family,
                           :noLinks => noLinks,
                           :editable => editable}) %>
  </li>
<% end %>
<% if option_for_more %>
  <li id='nodot'>
    <%= link_to "more action items...", 
                        :remote => true,
                        :url => {:controller => 'action_items',
                                 :action => 'list_closed_action_items',
                                 :conditions => conditions} %>
    <br>
  </li>
<% end %>
<script type="text/javascript">
    // TODO At some point it would be good to just update the dom, not refresh the whole thing, but for now, lets just refresh
    $('form.edit_action_item').on('ajax:success', function (event, xhr, status, error) {
        window.location.reload();
    });
    $('form.edit_action_item').on('ajax:error', function (event, xhr, status, error) {
        window.location.reload();
    });
</script>

app/views/action_items/_edit_action_item.html.erb
<% peopleList ||= nil %>
<% familyList ||= nil %>
<% redirect ||= 'family' %>
<fieldset class='teaching-record'>
  <legend> Edit Action Item </legend>
<%= form_for(edit_action_item, :url => {:controller => 'action_items', 
            :action => 'update', :id => edit_action_item.id })  do |f| %>
  <%= f.error_messages %>
  <p>
    <div style='float:left'>
      Ward Representative:<br>
      <%= f.select :person_id, peopleList %>
    </div>
    <div style='float:right'>
      Family:<br>
      <%= f.select :family_id, familyList, {:include_blank => true} %> 
    </div>
  </p>
  <p>
    <br> <br> 
  </p>
  <p>
    Assignment:<br>
    <%= f.text_area :action, :cols => 80, :rows => 1%>
  </p>
  <p>
    Due Date
    <%= f.date_select :due_date, :default => 7.days.from_now %>
  </p>
  <p>
    Other Comments:<br>
    <%= f.text_area :comment, :cols => 60, :rows => 1%>
  </p>
  <p>
    Requested by: <%= Person.find(edit_action_item.issuer_id).full_name %>
  </p>
    
  <p>
    <%= f.submit 'update' %> &nbsp; &nbsp;
    <%= link_to 'Cancel', :back %>
    <% if edit_action_item.issuer_id == session[:user_id] %>
      <%= button_to 'Delete', action_item_path(edit_action_item), :method => :delete %>
    <% end %>
  </p>
<% end %>
</fieldset>

app/views/action_items/_family_action_items.html.erb
<% unless @family.action_items().empty? %>
  <li> 
    <a href='#' class='subtile-links' onclick="Effect.toggle('family-action-items', 'blind'); 
      return false;">Action Items</a>
    <div id="family-action-items">
      <div>
        <ul>
          <div id='open-actions'>
            <%= render(:partial => 'action_items/action_items', 
                       :object => @family.open_action_items, 
                       :locals => {:checkbox => true,
                                   :ward_representative => true,
                                   :editable => true} ) %>
          </div>
          <br>
          <div id='closed-actions'>
            <%= render(:partial => 'action_items/action_items', 
                       :object => @family.closed_action_items[0..@limit-1], 
                       :locals => {:checkbox => true,
                                   :ward_representative => true,
                                   :editable => true,
                                   :listLimit => @limit,
                                   :option_for_more => (@family.closed_action_items[@limit] != nil),
                                   :conditions => "family_id==#{@family.id}"}) %>
          </div>
        </ul>
      </div>
    </div>
  </li>
<% end %>

app/views/action_items/_new_action_item.html.erb
<% peopleList ||= nil %>
<% familyList ||= nil %>
<% redirect ||= 'family' %>
<% assignee ||= nil %>
<%= form_for(@new_action_item, :url => {:controller => 'action_items', 
            :action => 'create', :redirect => redirect})  do |f| %>
  <%= f.error_messages %>
  <p>
    Ward Representative 
    <% if assignee != nil %>
      <%= f.select :person_id, peopleList, {:selected => assignee.id} %> <br />
    <% else %>
      <%= f.select :person_id, peopleList, {:selected => session[:user_id]} %> <br />
    <% end %>
  </p>
  <p>
    For Family 
    <%= f.select :family_id, familyList, {:include_blank => true} %> <br />
    Assignment <br />
    <%= f.text_area :action, :cols => 75, :rows => 1%>
  </p>
  <p>
    Due Date
    <%= f.date_select :due_date, :default => 7.days.from_now %>
  </p>
  <p>
    <%= f.submit 'Create' %>
    &nbsp;
    <%= link_to 'Cancel', :back %>
  </p>
<% end %>

app/views/action_items/_new_action_item_for_family.html.erb
<% form_for(@action_item, :url => {:controller => 'action_items', 
            :action => 'create', :redirect => 'family'})  do |f| %>
  <%= f.error_messages %>
  <p>
    Ward Representative 
    <%= f.select :person_id, @names, {:selected => session[:user_id]} %> <br />
  </p>
  <p>
    <%= f.hidden_field :family_id %>
    Assignment <br />
    <%= f.text_area :action, :cols => 75, :rows => 1%>
  </p>
  <p>
    Due Date
    <%= f.date_select :due_date, :default => 7.days.from_now %>
  </p>
  <p>
    <%= f.submit 'Create' %>
    &nbsp;
    <%= link_to 'Cancel', family_path(@action_item.family) %>
  </p>
<% end %>

app/views/action_items/_new_family_action_item.html.erb
<% action_item ||=nil %>
<% peopleList  ||=nil %>

<%= form_for(action_item, :url => {:controller => 'action_items', 
            :action => 'create', :redirect => 'family'})  do |f| %>
  <%= f.error_messages %>
  <p>
    Ward Representative 
    <%= f.select :person_id, peopleList, {:selected => session[:user_id]} %> <br />
  </p>
  <p>
    <%= f.hidden_field :family_id %>
    Assignment <br />
    <%= f.text_area :action, :cols => 75, :rows => 1%>
  </p>
  <p>
    Due Date
    <%= f.date_select :due_date, :default => 7.days.from_now %>
  </p>
  <p>
    <%= f.submit 'Create' %>
    &nbsp;
    <%= link_to_function 'Cancel',  "$('#new-action').hide(); $('#actionButtons').show();" %>
  </p>
<% end %>

app/views/action_items/edit.html.erb
<h1>Editing action_item</h1>

<%= form_for(@action_item) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :family_id %><br />
    <%= f.select :family_id, @familyList, {:include_blank => true} %>
  </p>
  <p>
    Assignee
    <%= f.select :person_id, @personList%>
  </p>
  <p>
    <%= f.label :action %><br />
    <%= f.text_area  :action, :cols=>50, :rows=>2 %>
  </p>
  <p>
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </p>
  <p>
    <%= f.label :status %><br />
    <%= f.select :status, {'closed' => 'closed','open' => 'open'} %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :cols=>50, :rows=>2 %>
  </p>
  <p>
    <%= f.label :issuer_id %><br />
    <%= @action_item.issuer.full_name unless @action_item.issuer.nil? %>
  </p>
  <p>
    <%= f.submit 'Update' %>
    <%= link_to "Cancel", :back %>
  </p>
<% end %>

app/views/action_items/index.html.erb
<h1>Listing action_items</h1>

<table>
  <tr>
    <th>Assignee</th>
    <th>Family</th>
    <th>Action</th>
    <th>Due date</th>
    <th>Status</th>
    <th>Issuer</th>
    <th colspan="3">Actions</th>
  </tr>

<% @action_items.each do |action_item| %>
  <tr>
    <td><%= action_item.person.full_name %></td>
    <td><%= action_item.family.name %></td>
    <td><%= action_item.action %></td>
    <td><%= action_item.due_date %></td>
    <td><%= action_item.status %></td>
    <td><%= action_item.author %></td>
    <td><%= link_to 'Show', action_item %></td>
    <td><%= link_to 'Edit', edit_action_item_path(action_item) %></td>
    <td><%= button_to 'Destroy', action_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New action_item', new_action_item_path %>

app/views/action_items/new.html.erb
<h1>New action_item</h1>

<%= form_for(@action_item) do |f| %>
  <%= f.error_messages %>

  <p>
  <%= f.label :family_id %><br />
  <%= f.select :family_id, options_for_select(Family.all.map { |fam| [fam.full_name, fam.id] }) %>
  </p>
  <p>
  <%= f.label :person_id %><br />
  <%= f.select :person_id, options_for_select(Person.all.map { |p| [p.full_name, p.id] }) %>
  </p>
  <p>
  <%= f.label :action %><br />
  <%= f.text_area :action %>
  </p>
  <p>
  <%= f.label :due_date %><br />
  <%= f.date_select :due_date %>
  </p>
  <p>
  <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', action_items_path %>

app/views/action_items/show.html.erb
<p>
  <b>Family:</b>
  <%= link_to @action_item.family.full_name, @action_item.family %>
</p>

<p>
  <b>Person Assigned:</b>
  <%=link_to @action_item.person.full_name, @action_item.person %>
</p>

<p>
  <b>Action:</b>
  <%=h @action_item.action %>
</p>

<p>
  <b>Due date:</b>
  <%=h @action_item.due_date %>
</p>

<p>
  <b>Status:</b>
  <%=h @action_item.status %>
</p>

<p>
<b>Issuer:</b>
  <%= link_to @action_item.issuer.full_name, person_path(@action_item.issuer) %>
</p>


<%= link_to 'Edit', edit_action_item_path(@action_item) %> |
<%= link_to 'Back', action_items_path %>

app/views/action_items/wardActionItems.html.erb
<script type="text/javascript">
function showElement(divId) {
  var div = document.getElementById(divId);
  div.style.display = "inline";
}
function hideElement(divId) {
  var div = document.getElementById(divId);
  div.style.display = "none";
}
</script>

<h1>Ward Action Items

  <div id='actionButtons' > &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     
    <%= button_to_function("New Action Item", "showElement('new-action');
                                               hideElement('actionButtons');")%>
  </div>
</h1>

<div id = 'new-action' style='display:none;'> 
  <%= render(:partial => 'action_items/new_action_item', 
             :object => @new_action_item,
             :locals => {:peopleList => @names,
                         :redirect => 'ward',
                         :familyList => @families}) %>
  <hr>
</div>

<ul>
  <% @person_actions.each do |assignee, tasks| %>
    <li> 
      <div id='open-actions' 
           class = "cell"
           onclick="window.location.href='<%= url_for(:controller => 'users',
                                                      :action => 'todo',
                                                      :id => assignee.id ) %>'" >
        <%= assignee.full_name %>
        <ul>
          <%= render(:partial => "action_items/action_items",
                     :object => tasks,
                     :locals => {:family => true,
                                 :style => "id='square'",
                                 :noLinks => true}
                    ) %>
        </ul>
      </div>
      <br>
    </li>
  <% end %>
</ul>
  <br>
  <div id='closed-actions'>
    <%= render(:partial => 'action_items/action_items', 
               :object => @closed_action_items,
               :locals => {:ward_representative => true,
                       :family => true,
                       :editable => true,
                       :style => "id='square'"}
    
              ) %>
  </div>
<br><br>